from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import HexColor, white
from reportlab.pdfbase import pdfmetrics

styles = getSampleStyleSheet()

title_style = styles["Title"]
title_style.alignment = TA_CENTER
title_style.textColor = HexColor("#0F766E")

heading = styles["Heading2"]
heading.textColor = HexColor("#0F766E")

body = styles["BodyText"]
body.leading = 20


def create_pdf(
    filename,
    date,
    total_hours,
    score,
    most_used_app,
    report
):

    pdf = SimpleDocTemplate(filename)

    story = []

    story.append(
        Paragraph(
            "<font size='24'><b>Life-OS Wellbeing Report</b></font>",
            title_style
        )
    )

    story.append(
        Paragraph(
            "<font color='#64748B'>Your Personalized AI Digital Wellness Summary</font>",
            styles["Italic"]
        )
    )

    story.append(Spacer(1, 25))

    if score >= 80:
        score_color = "#22C55E"

    elif score >= 60:
        score_color = "#F59E0B"

    else:
        score_color = "#EF4444"

    table = Table(
        [
            ["Date", str(date)],
            ["Screen Time", f"{total_hours} Hours"],
            ["Productivity Score", f"{score}/100"],
            ["Most Used App", most_used_app],
        ],
        colWidths=[170, 250],
    )

    table.setStyle(
        TableStyle(
            [

                ("BACKGROUND", (0, 0), (0, -1), HexColor("#E6FFFA")),

                ("TEXTCOLOR", (0, 0), (0, -1), HexColor("#0F766E")),

                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),

                ("GRID", (0, 0), (-1, -1), .5, HexColor("#CBD5E1")),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 12),

                ("TOPPADDING", (0, 0), (-1, -1), 12),

            ]
        )
    )

    story.append(table)

    story.append(Spacer(1, 25))

    story.append(
        Paragraph(
            f"<font color='{score_color}' size='18'><b>Wellness Score : {score}/100</b></font>",
            heading,
        )
    )

    story.append(Spacer(1, 20))

    story.append(Paragraph("✅ Strengths", heading))

    for item in report["strengths"]:
        story.append(
            Paragraph(f"• {item}", body)
        )

    story.append(Spacer(1, 15))

    story.append(Paragraph("⚠ Needs Attention", heading))

    for item in report["issues"]:
        story.append(
            Paragraph(f"• {item}", body)
        )

    story.append(Spacer(1, 15))

    story.append(Paragraph("🎯 Action Plan", heading))

    for item in report["actions"]:
        story.append(
            Paragraph(f"• {item}", body)
        )

    story.append(Spacer(1, 15))

    story.append(Paragraph("🚀 Tomorrow's Challenge", heading))

    story.append(
        Paragraph(
            report["challenge"],
            body,
        )
    )

    story.append(Spacer(1, 30))

    story.append(
        Paragraph(
            "<font color='#0F766E'><b>Generated by Life-OS AI Wellbeing Dashboard</b></font>",
            styles["Italic"],
        )
    )

    pdf.build(story)